### ISSUE TITLE
Download data error

### ISSUE THREAD

**Issue by zoulixin93** [minerllabs/competition_submission_starter_template#1]
Attempting to download the dataset...
Server does not support HTTPRange. threads_count is set to 1.
URL error encountered when downloading - please try again
None
Data verified! A+!

**Comment by brandonhoughton** [comment]
I've never seen this issue - our servers do support HTTP Range, my guess is that your internet connection was flaky. Could you try again with debug logging and post your console output?

**Comment by brandonhoughton** [comment]
Fixed now! This was an HTTPS certificate issue
