### ISSUE TITLE
Pretrain model size limit

### ISSUE THREAD

**Issue by kimbring2** [minerllabs/competition_submission_starter_template#10]
Hello, I am one of competition participant

I want to upload my Tensorflow model weight file with a competition_submission_starter_template.
But, I can not upload it on a Gitlab of Aicrowd because of limit uploading size. 

I try to find a way for extending that limit. However, I can not find it.

Please help me!
Thank you.

**Comment by brandonhoughton** [comment]
@skbly7 What is the current limit for upload size? This will be an issue for all participants uploading models for round 1!

**Comment by kimbring2** [comment]
Current limit is 10MB. Thus, I changed my previous model that include LSTM to only CNN one.

**Comment by brandonhoughton** [comment]
Would your model fit in 100 MB?

**Comment by kimbring2** [comment]
Yes, it is around 42MB.

**Comment by spMohanty** [comment]
@kimbring2 : You can use [git-lfs](https://git-lfs.github.com/) to check in your model weights which are larger than 10MB. 
Please do remember to use [`git lfs migrate`](https://github.com/git-lfs/git-lfs/wiki/Tutorial#using-git-lfs-migrate) to remove the large files from your git history.

Then you should be able to check in and push your model weights for evaluation.

**Comment by kimbring2** [comment]
@spMohanty @brandonhoughton Thank you very much for helping me!!
