### ISSUE TITLE
Which files are allowed to be modified by participants?

### ISSUE THREAD

**Issue by kaixin96** [minerllabs/competition_submission_starter_template#13]
Are we allowed to modify some files (e.g. `train_locally.sh`)? When evaluated on the server, will `train_locally.sh` or `docker_train_locally.sh` be called?

**Comment by skbly7** [comment]
The entry point while running submission will be `main()` in `train.py` & `test.py` for both stages respectively. 

The utility/helper script files such as `*_locally.sh` are to make running on self's machine straight forward/easier, and they wouldn't be call during online submission.

Please let us know if you have any follow up question.
