### ISSUE TITLE
Using MineRLNavigate-v0, MineRLTreechop-v0, MineRLObtainIronPickaxe-v0 dataset

### ISSUE THREAD

**Issue by kimbring2** [minerllabs/competition_submission_starter_template#15]
Should I use MineRLObtainDiamond-v0 dataset only when training? Or Can I use the dataset listed in the title? MineRLObtainDiamond-v0 has the inconvenience that data must be separated before using.

**Comment by brandonhoughton** [comment]
All environments are available during training!
Evaluation is the only phase where we restrict all agents to the MineRLObtainDiamond-v0 environment.
