### ISSUE TITLE
My submission episode always ends after eposide 1 

### ISSUE THREAD

**Issue by kimbring2** [minerllabs/competition_submission_starter_template#17]
Below is my latest submission result. It ended only doing eposide 1. 

![02-44-41](https://user-images.githubusercontent.com/11064407/64637177-385a1780-d43e-11e9-8670-2bdce9a1fd27.png)

When I run an evaluation_locally.sh file, I can see a many eposide like below.
![02-44-58](https://user-images.githubusercontent.com/11064407/64637368-938c0a00-d43e-11e9-958f-5a64ff86f3a5.png)

I can not find a problem about that problem.

**Comment by 50infivedays** [comment]
i have exactly the same issue , need help~

**Comment by kimbring2** [comment]
@50infivedays I can not solve that issue and forgive submission fianlly. 
I succeed in collecting stones, but I am very sorry that I can not submit my result.

**Comment by 50infivedays** [comment]
@kimbring2 really sad about this
