### ISSUE TITLE
Question regarding maximum file size (for trained agent models)

### ISSUE THREAD

**Issue by Danielhp95** [minerllabs/competition_submission_starter_template#26]
Hello!

My team and I are really struggling to upload an agent that is smaller than the maximum size allowed by Gitlab (`10MB`), as our model weighs around `96MB`.

We were wondering if we can use `git lfs` (large file system), to upload our agent. This will mean that these two commands: `git lfs install` and `gi lfs pull` should be run on the machine running the test code for Round 1.

Thank you!

**Comment by skbly7** [comment]
I hope you used `git lfs` in the 2020 edition, and we would love to see you around in [this year's challenge](https://www.aicrowd.com/challenges/neurips-2021-minerl-diamond-competition) or [BASALT challenge](https://www.aicrowd.com/challenges/neurips-2021-minerl-basalt-competition/). 👋 

---

For future users facing similar issue:
`git lfs` is enabled on GitLab using which you can upload larger models and files. [[How To]](https://discourse.aicrowd.com/t/how-to-upload-large-files-size-to-your-submission/2304)
